---
git:
  depth: 5
language: cpp
sudo: required

services:
  - docker

before_install:
  - 'sed -i "s/rpmbuild_uid\: 1000/rpmbuild_uid\: $(id -u)/" config.yml'

jobs:
  include:
    - stage: lint
      script:
        - |
          docker run \
            -v $TRAVIS_BUILD_DIR:/rpmbuild/hootenanny-rpms:rw \
            -w /rpmbuild/hootenanny-rpms \
            -it --rm \
            hootenanny/rpmbuild-check@sha256:79d86c2a4a56df2752dfb78696974e17c149454fc15dc684b877ddab099962f3 \
            bash -c "./tests/lint-yaml.sh && ./tests/lint-bash.sh"
    - stage: rpm
      script:
        - |
          sudo apt-get update -qq
          sudo apt-get install -qq -y rpm
          ./scripts/vagrant-install.sh
          MAVEN_CACHE=0 vagrant validate
          make rpmbuild-hoot-release
          make archive
          make --version
          make -d -n rpm
