---
version: 2

jobs:
  lint:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-check@sha256:79d86c2a4a56df2752dfb78696974e17c149454fc15dc684b877ddab099962f3
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint YAML and Scripts'
          command: ./tests/lint-yaml.sh && ./tests/lint-bash.sh
  rpm:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools'
          command: |
            sudo apt-get -y update
            sudo apt-get -y install rpm
      - run:
          name: 'Install Vagrant'
          command: |
            ./scripts/vagrant-install.sh
      - run:
          name: 'Validate Vagrantfile'
          command: |
            MAVEN_CACHE=0 vagrant validate
      - run:
          name: 'make rpmbuild-hoot-release'
          command: |
            make rpmbuild-hoot-release
      - run:
          name: 'make archive'
          command: |
            make archive
      - run:
          name: 'make rpm'
          command: |
            make rpm

workflows:
  version: 2
  tests:
    jobs:
      - lint
      - rpm:
          requires:
            - lint
