---
version: 2

jobs:
  lint-bash:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-check@sha256:79d86c2a4a56df2752dfb78696974e17c149454fc15dc684b877ddab099962f3
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint Bash Scripts'
          command: ./tests/lint-bash.sh
  lint-yaml:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-check@sha256:79d86c2a4a56df2752dfb78696974e17c149454fc15dc684b877ddab099962f3
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint YAML Files'
          command: ./tests/lint-yaml.sh
  test-vagrant:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools'
          command: |
            sudo apt-get -y update
            sudo apt-get -y install rpm
      - run:
          name: 'Install Vagrant'
          command: |
            ./scripts/vagrant-install.sh

      - run:
          name: 'Validate Vagrantfile'
          command: |
            MAVEN_CACHE=0 vagrant validate
      - run:
          name: 'Create rpmbuild-generic'
          command: |
            make rpmbuild-hoot-release

workflows:
  version: 2
  tests:
    jobs:
      - lint-bash
      - lint-yaml
      - test-vagrant:
          requires:
            - lint-bash
            - lint-yaml
