---
version: 2

jobs:
  lint-bash:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-check@sha256:79d86c2a4a56df2752dfb78696974e17c149454fc15dc684b877ddab099962f3
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint YAML Files'
          command: ./tests/lint-yaml.sh
  lint-yaml:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-check@sha256:79d86c2a4a56df2752dfb78696974e17c149454fc15dc684b877ddab099962f3
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint Bash Scripts'
          command: ./tests/lint-bash.sh

workflows:
  version: 2
  tests:
    jobs:
      - lint-bash
      - lint-yaml
